version: '2'
services:
  maven:
      build:
        context: dockerfiles
        dockerfile: dockerfiles/dockerfile-maven
      volumes:
        - ~/.m2:/root/.m2
        - $PWD:/usr/src/mavenprojects
      volumes_from:
        - tomcat
      network_mode: bridge
  tomcat:
    build:
      context: dockerfiles
      dockerfile: dockerfiles/dockerfile-tomcat
    ports:
      - "8080:8080"