version: '2'
services:
  maven:
    image: dzhangrlv/docker-compose-maven:1.0
    links:
      - tomcat
    volumes:
      - ~/.m2:/root/.m2
    volumes_from:
      - tomcat
    #network_mode: bridge
  tomcat:
    image: dzhangrlv/docker-compose-tomcat:1.0
    ports:
      - "8080:8080"